name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: abdo8558/myapp:${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./bulletin-board-app
          file: ./bulletin-board-app/Dockerfile
          tags: ${{ env.DOCKER_IMAGE }}, abdo8558/myapp:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64  # Spécifiez l'architecture

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Create ~/.kube directory
        run: mkdir -p ~/.kube

      - name: Configure Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml --insecure-skip-tls-verify
          kubectl apply -f k8s/service.yaml --insecure-skip-tls-verify
      - name: Update Kubernetes Deployment Image
        run: |
          kubectl set image deployment/myapp myapp=${{ env.DOCKER_IMAGE }} --insecure-skip-tls-verify
          kubectl rollout restart deployment/myapp --insecure-skip-tls-verify

      - name: Check the Pods
        run: |
          kubectl get pods -o wide --insecure-skip-tls-verify